#!/bin/bash
# LIGHTNING-KERNEL-BUILD

# Variables
DIR="$(pwd)"

PARENT_DIR="$(pwd)"

echo "Cloning dependencies"
git clone --depth=1 --branch stock_a90 https://github.com/young0103/samsung_a90_kernel kernel
cd kernel 
git clone --depth=1 --branch android-11.0.0_r48 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 aarch64-linux-android-4.9
git clone --depth=1  https://github.com/prorooter007/android_prebuilts_clang_host_linux-x86_clang-6877366 clang-r383902
git clone --depth=1 https://github.com/osm0sis/AnyKernel3 AnyKernel3
echo "Done"
KERNEL_DIR=$(pwd)
OUT_DIR="$(pwd)/out"
REPACK_DIR="${KERNEL_DIR}/AnyKernel3"
IMAGE="${KERNEL_DIR}/arch/arm64/boot/Image"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"


export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export CROSS_COMPILE="$(pwd)/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
export CLANG_TRIPLE="$(pwd)/clang-r383902/bin/aarch64-linux-gnu-"
export ARCH=arm64
export SEC_BUILD_CONF_VENDOR_BUILD_OS=13
export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN="$(pwd)/aarch64-linux-android-4.9/bin"
export CLANG_PREBUILT_BIN="$(pwd)/clang-r383902/bin"
export PATH=$PATH:$LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN:$CLANG_PREBUILT_BIN
export LLVM=1
#KERNEL_MAKE_ENV="LOCALVERSION=-Lightning-V2.5"

# Color
ON_BLUE=`echo -e "\033[44m"`	# On Blue
BRED=`echo -e "\033[1;31m"`	# Bold Red
BBLUE=`echo -e "\033[1;34m"`	# Bold Blue
BGREEN=`echo -e "\033[1;32m"`	# Bold Green
UNDER_LINE=`echo -e "\e[4m"`	# Text Under Line
STD=`echo -e "\033[0m"`		# Text Clear
 
build_kernel(){  
  export ARCH=arm64
### ───────────────── DEBUG BLOCK ─────────────────
  echo "=== DEFCONFIG analyzing ==="
  echo "PWD               : $(pwd)"
  echo "current branch        : $(git rev-parse --abbrev-ref HEAD)"
  echo "ARCH env          : ${ARCH:-<unset>}"
  echo "file?        : $(test -f arch/arm64/configs/r3q_kor_single_defconfig && echo YES || echo NO)"
  echo "ls | grep r3q     :" ; ls arch/arm64/configs | grep -i r3q || echo "(none)"
  echo "make recognize ARCH:"
  make -s -C . --no-print-directory -f Makefile -p | grep -m1 "^ARCH =" 
  echo "================================================"
### ───────────────────────────────────────────────
  echo "${BGREEN}***** Compiling kernel *****${STD}"
  [ ! -d "$OUT_DIR" ] && mkdir $OUT_DIR
  make -j$(nproc) -C "$KERNEL_DIR" $KERNEL_MAKE_ENV r3q_kor_single_defconfig
  make -j$(nproc) -C "$KERNEL_DIR" $KERNEL_MAKE_ENV

  [ -e "$(pwd)/arch/arm64/boot/Image.gz" ] && cp "$(pwd)/arch/arm64/boot/Image.gz" $OUT_DIR/Image.gz
  if [ -e "$(pwd)/arch/arm64/boot/Image" ]; then
    cp "$(pwd)/arch/arm64/boot/Image" $OUT_DIR/Image

    DTB_DIR=$(pwd)/arch/arm64/boot/dts
    $(pwd)/tools/mkdtimg cfg_create $(pwd)/out/dtb.img dt.configs/exynos2100.cfg -d ${DTB_DIR}/exynos
    $(pwd)/tools/mkdtimg cfg_create $(pwd)/out/dtbo.img dt.configs/r9s.cfg -d ${DTB_DIR}/samsung/r9s
    echo "${BGREEN}***** Ready to Roar *****${STD}"
  fi

  
  if [ -e "$(pwd)/arch/arm64/boot/Image" ]; then
    cd "$(pwd)/AnyKernel3"
    git reset --hard
    cp $IMAGE zImage
    cp $OUT_DIR/dtbo.img dtbo.img
    sed -i "s/ExampleKernel by osm0sis/r3q_kor_single Stock kernel by prorooter007/g" anykernel.sh
    sed -i "s/=maguro/=r9s/g" anykernel.sh
    sed -i "s/=toroplus/=/g" anykernel.sh
    sed -i "s/=toro/=/g" anykernel.sh
    sed -i "s/=tuna/=/g" anykernel.sh
    sed -i "s/platform\/omap\/omap_hsmmc\.0\/by-name\/boot/bootdevice\/by-name\/boot/g" anykernel.sh
    sed -i "s/backup_file/#backup_file/g" anykernel.sh
    sed -i "s/replace_string/#replace_string/g" anykernel.sh
    sed -i "s/insert_line/#insert_line/g" anykernel.sh
    sed -i "s/append_file/#append_file/g" anykernel.sh
    sed -i "s/patch_fstab/#patch_fstab/g" anykernel.sh
    zip -r9 "$(pwd)/r3q_kor_single_kernel_.zip" * -x .git README.md *placeholder
    
    curl https://bashupload.com/$REPACK_DIR/r3q_kor_single_kernel_.zip --data-binary @$REPACK_DIR/r3q_kor_single_kernel_.zip
  fi
}

gsi_kernel(){
  echo "${BGREEN}***** Apply GSI patch *****${STD}"

  cd $KERNEL_DIR
  git apply gsi-commits.patch
}

build_kernel

gsi_kernel

build_kernel
